name: Release
on:
  push:
    tags:
      - "*"
concurrency:
  group: release-gh
  cancel-in-progress: true
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        target:
          - { goos: darwin, goarch: arm64 }
          - { goos: darwin, goarch: amd64 }
          - { goos: linux, goarch: amd64 }
          - { goos: linux, goarch: arm }
          - { goos: windows, goarch: amd64 }
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20
      - name: Build
        run: go build -o bin/wheely-${{ matrix.target.goos}}-${{ matrix.target.goarch}}${{ matrix.target.goos == "windows" && ".exe" || "" }} -v
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: bin/*
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Install packages
        run: pip install binary_wheel_builder[cli] twine
      - name: Prepare wheel
        run: binary-wheel-builder --wheel-spec wheely-wheel.yaml
      - name: Publish
        run: twine upload -r pypi dist/*
        env:
          TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
          TWINE_NON_INTERACTIVE: true